### ISSUE TITLE
Separate Driver and Operator controls

### ISSUE THREAD

**Issue by gabeseq** [Team4028/2024-Crescendo#21]

**Comment by ghost** [comment]
Commands we need:
- manual pivot control
- real climbing controls (possibly one button to cycle through)
- possible infeed backout
- Real manual pivot control (hold position after letting go)
- Auto fan control?
- X-Drive

As of now, what we want is:
Driver:
- LT: Dumb infeed
- RT: go feeeeeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaast
- B: Smart infeed
- X: X-drive
- Start: zero drivetrain
- Back: Add Measurement (+down = reset)
- LB/RB: Climber down/up

Operator:
- X: Magic Shoot
- B: Manual Shoot (pivot & shooter both)
- A: Run conveyor
- Y: Climber (center: zero, up: ready, left: down one, right: down two, down: climb) -- should be a cycle in the future
- LB/RB: Pivot Down/Up
